from handlers.client.request_form import register_handlers_request_form
from handlers.client.start import register_handlers_start
from handlers.client.info import register_handlers_info
from handlers.client.request_form import Form